### PR TITLE
Add support for PHP 7.2

### PR DESCRIPTION
**Pull request by roukmoute**
To merge once https://github.com/memio/twig-template-engine/pull/7 is merged.

I've update version for `model` and `twig-template-engine` because I suppose we must update theses version, is it correct?

### CODE REVIEW

**Comment by gnugat** [comment]
Thank you for your contribution. I've rather released them as a bug fix (v2.0.1), so the lat change needed for this PR is to switch back the versions constraints.

**Comment by jakzal** [comment]
ping :)

**Comment by roukmoute** [comment]
Ouh sorry I haven't seen that!
I will do that.

**Comment by roukmoute** [comment]
Is it ok now or I update `branch-alias` too?

**Comment by roukmoute** [comment]
Is it ok?

**Comment by gnugat** [comment]
that's perfect, thanks :+1:

**Comment by roukmoute** [comment]
🆒 I wait new release now

EDIT: So fast 😎

**Comment by gnugat** [comment]
The wait is over, released as spec-gen v0.8.4 :)

**Pull request merged**
